### ISSUE TITLE
TDP IAM Authentication Does Not Work in Some Environments

### ISSUE THREAD

**Issue by EdwardOst** [Talend/ansible-talend-platform#22]
The TDP authentication does not work when TDP is on a different host from IAM or when there are different public and private IP addresses for the servers.  Even when setting all relevant variables to public hostnames the TDP login is displayed by an error is returned when the actual login attempt is made.

> : ( Oops! Something went wrong in IAM Talend OIDC Server.
> Due to an internal server error or misconfiguration, your request could not be completed.
> Please contact your administrator to check the configuration.

**Comment by sgolovnya** [comment]
Unfortunately we were not able to reproduce this issue with 7.3 release.
Was it provoked with more older release? 7.2 is end-of-live in April 2021.
If this issue is still actual, please create a new Jira in TINSTL project (and we will close Issues section and instead we will ask to create Jiras in TINSTL project which is much more under control.
